// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCuh5P2q0aglD6TVf8Rs5e0M2NJAxwuqs',
    appId: '1:436288419399:web:d667a2c2c06c3c2f59a362',
    messagingSenderId: '436288419399',
    projectId: 'calmcampus-c7f77',
    authDomain: 'calmcampus-c7f77.firebaseapp.com',
    storageBucket: 'calmcampus-c7f77.firebasestorage.app',
    measurementId: 'G-7C56NG471T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvyyrZmvugchaZPM7zIqWJWHWjtEhesx4',
    appId: '1:436288419399:android:ef304f98457f2e8959a362',
    messagingSenderId: '436288419399',
    projectId: 'calmcampus-c7f77',
    storageBucket: 'calmcampus-c7f77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKlsp8rdEwifmQ6MVQCoGpUyykntk5Ug4',
    appId: '1:436288419399:ios:b19d345cf3f4295b59a362',
    messagingSenderId: '436288419399',
    projectId: 'calmcampus-c7f77',
    storageBucket: 'calmcampus-c7f77.firebasestorage.app',
    iosBundleId: 'com.example.calmcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKlsp8rdEwifmQ6MVQCoGpUyykntk5Ug4',
    appId: '1:436288419399:ios:b19d345cf3f4295b59a362',
    messagingSenderId: '436288419399',
    projectId: 'calmcampus-c7f77',
    storageBucket: 'calmcampus-c7f77.firebasestorage.app',
    iosBundleId: 'com.example.calmcampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCuh5P2q0aglD6TVf8Rs5e0M2NJAxwuqs',
    appId: '1:436288419399:web:53493bdb684837f459a362',
    messagingSenderId: '436288419399',
    projectId: 'calmcampus-c7f77',
    authDomain: 'calmcampus-c7f77.firebaseapp.com',
    storageBucket: 'calmcampus-c7f77.firebasestorage.app',
    measurementId: 'G-606T2CDSEH',
  );
}
